version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    environment:
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
